title: Rupesh Bhandari
iconURL: assets/default-icon.png
theme: jekyll-theme-console

# for a clean URL
permalink: :slug

social:
  twitter: rupesh_bhandari
  github: rpshbhandari

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: G-S9N4FHXF55
